apiVersion: v1
kind: Service
metadata:
  name: music-player
  labels:
    app: music-player
spec:
  # ClusterIP is sufficient as devices communicate internally with the 'server'
  type: ClusterIP
  ports:
    # Port for the device's internal application logic, 
    # typically the one used for discovery/communication with the server (30000)
    - port: 30000
      targetPort: 30000
  selector:
    app: music-player
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-player
  labels:
    app: music-player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-player
  template:
    metadata:
      labels:
        app: music-player
    spec:
      containers:
        - name: music-player
          image: corradostortini2/domoticasw-music-player@sha256:a5e032461d5a499abe77832a916f0e8a2fbda5a840809566aec2650ca64ec84a
          ports:
            - containerPort: 30000
          env:
            - name: SERVER_DISCOVERY_PORT
              value: "30000"
            - name: DISCOVERY_BROADCAST_ADDR
              value: "255.255.255.255"
            - name: PORT
              value: "30000"
            - name: SERVER_ADDRESS
              value: "server:3000"
            # music-player-specific environment variables:
            - name: MUSICS
              value: "Back in Black-255,Must Have Been the Wind-243,Eye of the Tiger-246,Don't Stop Me Now-209,INVISIBLE-191"
            - name: LAN_HOSTNAME
              value: "music-player"