name: Publish docker image
on:
  release:
    types: [released]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME_CORRADO }}
          password: ${{ secrets.DOCKERHUB_SECRET_MUSIC_PLAYER }}

      - name: Run sbt Docker/publish
        run: VERSION=${{github.event.release.tag_name}} sbt Docker/publish

      - name: Update DockerHub description from README
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME_CORRADO }}
          password: ${{ secrets.DOCKERHUB_SECRET_MUSIC_PLAYER }}
          repository: ${{ vars.DOCKERHUB_USERNAME_CORRADO }}/domoticasw-music-player
          short-description: A Music player device simulated for DomoticASW